wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.2
    framework: huggingface
    huggingface_version: 4.36.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1710252497.551894
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      - 71
      - 105
      2:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      - 71
      - 105
      3:
      - 7
      - 13
      - 23
      4: 3.11.5
      5: 0.16.2
      6: 4.36.2
      8:
      - 4
      - 5
      13: darwin-arm64
    m:
    - 1: trainer/global_step
      6:
      - 3
